GameShopRP/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameShopRP.Models
{
	public class Order
	{
		public int Id { get; set; }
		public DateTime OrderDate { get; set; }
		public bool IsCheckedOut { get; set; }

		public string ShopUserId { get; set; }
		public virtual ICollection<OrderLine> OrderLines { get; set; }
		public virtual ShopUser ShopUser { get; set; }
	}
}

GameShopRP/ViewModels/CatalogItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameShopRP.ViewModels
{
	public class CatalogItemViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public string Language { get; set; }
		public string Genre { get; set; }
		public string Publisher { get; set; }
		public decimal Price { get; set; }
		public string ImageUrl { get; set; }
	}
}

GameShopRP/ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GameShopRP.ViewModels
{
	public class OrderViewModel
	{
		public List<OrderItemViewModel> OrderItems { get; set; } = new List<OrderItemViewModel>();
		public string UserId { get; set; }

		public decimal Total()
		{
			return Math.Round(OrderItems.Sum(x => x.ProductPrice * x.Quantity), 2);
		}
	}
}

GameShopRP/Pages/CatalogItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GameShopRP.Models;
using GameShopRP.Services.Catalog;
using GameShopRP.Services.Order;
using GameShopRP.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GameShopRP.Pages
{
    public class CatalogItemModel : PageModel
	{
		private readonly ICatalogService _catalogService;
		private readonly IOrderService _orderService;
		private readonly UserManager<ShopUser> _userManager;
		private readonly SignInManager<ShopUser> _signInManager;

		public CatalogItemModel(ICatalogService catalogService, 
			IOrderService orderService, 
			UserManager<ShopUser> userManager,
			SignInManager<ShopUser> signInManager)
		{
			_catalogService = catalogService;
			_orderService = orderService;
			_userManager = userManager;
			_signInManager = signInManager;
		}

		public CatalogItemViewModel ItemModel { get; set; } = new CatalogItemViewModel();

		//public void OnGet()
  //      {
  //      }

		public async Task OnGetLoadItem(int prodId)
		{
			ItemModel = await _catalogService.GetCatalogItemByIdAsync(prodId);
		}

		public async Task<IActionResult> OnPostAddToCart(int prodId)
		{
			if (_signInManager.IsSignedIn(HttpContext.User))
			{
				var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
				await _orderService.AddItemToOrder(userId, prodId);
				//return RedirectToPage("CatalogItem", "LoadItem", new { prodId });
				return Redirect(string.Format("~/CatalogItem/LoadItem/{0}", prodId));
			} else
			{
				return Redirect("~/Identity/Account/Login");
			}
		}
    }
}

GameShopRP/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GameShopRP.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

GameShopRP/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameShopRP.Services.Catalog;
using GameShopRP.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GameShopRP.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ICatalogService _catalogService;

		public IndexModel(ICatalogService catalogService)
		{
			_catalogService = catalogService;
		}
		[BindProperty(SupportsGet = true)]
		public int CurrentPage { get; set; } = 1;
		public int Count { get; set; }
		public int PageSize { get; set; } = 10;

		public int TotalPages => (int)Math.Ceiling(decimal.Divide(Count, PageSize));

		public CatalogViewModel CatalogModel { get; set; } = new CatalogViewModel();

		public async Task OnGet()
		{
			CatalogModel = await _catalogService.GetCatalogItemsAsync(CurrentPage, 10, CatalogModel.PlatformsFilterApplied, CatalogModel.TypesFilterApplied);
			Count = CatalogModel.TotalCount;
		}

		public IActionResult OnPostViewItem(int prodId)
		{
			//return RedirectToPage("CatalogItem", "LoadItem", new { prodId });
			return Redirect(string.Format("~/CatalogItem/LoadItem/{0}", prodId));
		}
	}
}

GameShopRP/Pages/Order.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GameShopRP.Services.Order;
using GameShopRP.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GameShopRP.Pages
{
    public class OrderModel : PageModel
    {
		private readonly IOrderService _orderService;

		public OrderViewModel OrderViewModel { get; set; } = new OrderViewModel();

		public OrderModel(IOrderService orderService)
		{
			_orderService = orderService;
		}

        public async Task OnGet()
        {
			OrderViewModel = await _orderService.GetOrderItemsAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));
        }

		public async Task<IActionResult> OnPostDeleteOrderLine(int orderLineId)
		{
			await _orderService.DeleteOrderLine(orderLineId);
			return RedirectToPage("Order");
		}

		public async Task<IActionResult> OnPostUpdateQuantity(int orderLineId, int quantity)
		{
			await _orderService.UpdateQuantity(orderLineId, quantity);
			return RedirectToPage("Order");
		}
    }
}

GameShopRP/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GameShopRP.Pages
{
	public class PrivacyModel : PageModel
	{
		public void OnGet()
		{
		}
	}
}

GameShopRP/Pages/CatalogItem.cshtml
@page "{handler?}/{prodId?}"
@model GameShopRP.Pages.CatalogItemModel
@{
    ViewData["Title"] = "CatalogItem";
}

<div class="container">
    <div class="row my-2">
        <div class="col-3">
            <img class="img-fluid" src="@Model.ItemModel.ImageUrl">
        </div>
        <div class="col-6">
            <div class="pb-2">
                <div class="row">
                    <div class="col-auto text-secondary">Genre: </div>
                    <div class="col-auto">@Model.ItemModel.Genre</div>
                    <p> | </p>
                    <div class="col-auto text-secondary">Language: </div>
                    <div class="col-auto">@Model.ItemModel.Language</div>
                </div>
            </div>
            <div>
                <h1 class="text-dark">@Model.ItemModel.Name</h1>
            </div>
            <hr />
            <div>@Model.ItemModel.Description</div>
        </div>
        <div class="col-3">
            <div>@Model.ItemModel.Price</div>
            <form asp-page-handler="addtocart" method="post">
                <button id="addToCart" type="submit" class="btn btn-success">Add to cart</button>
                <input type="hidden" asp-for="@Model.ItemModel.Id" name="prodId" />
            </form>

        </div>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>

        $(function () {
        $.ajax({  
                type: "GET",  
                contentType: "application/json; charset=utf-8",  
                datatype: "json",  
                success: function () {  
                    debugger;
                    $('#myModal').modal('show');                    
  
                },  
                error: function () {  
                    alert("Dynamic content load failed.");  
                }  
            });  
        $("#closbtn").click(function () {
            $('#myModal').modal('hide');
        });
    });

    </script>  
}

GameShopRP/Pages/Index.cshtml
@page
@{
    ViewData["Title"] = "Catalog";
    @model IndexModel
}

@*<section class="catalog-filters">
    <div class="container">
        <form method="get">
            <label class="catalog-label" data-title="brand">
                <select asp-for="@Model.CatalogModel.PlatformsFilterApplied" asp-items="@Model.CatalogModel.Platforms" class="catalog-filter"></select>
            </label>
            <label class="catalog-label" data-title="type">
                <select asp-for="@Model.CatalogModel.TypesFilterApplied" asp-items="@Model.CatalogModel.Types" class="catalog-filter"></select>
            </label>
            <input class="catalog-send" type="image" src="images/arrow-right.svg" />
        </form>
    </div>
</section>
<div class="container">*@
    @if (Model.CatalogModel.CatalogPageItems.Any())
    {
        <div class="row">
            @foreach (var catalogItem in Model.CatalogModel.CatalogPageItems)
            {
                <div class="col-md-3 my-2">
                    <form asp-page-handler="viewitem" method="post">
                        <button class="catalog-button-hidden" type="submit">
                            <div class="card">
                                <img class="card-img-top" src="@catalogItem.ImageUrl">
                                <div class="card-body">
                                    <h5 class="card-title">@catalogItem.Name</h5>
                                    <p class="card-text">$@catalogItem.Price</p>
                                </div>
                            </div>
                        </button>
                        <input type="hidden" asp-for="@catalogItem.Id" name="prodId" />
                    </form>
                </div>
            }
        </div>
        @*<partial name="_pagination" for="CatalogModel.PaginationInfo" />*@
    }
    else
    {
        <div class="catalog-items row">
            THERE ARE NO RESULTS THAT MATCH YOUR SEARCH
        </div>
    }
</div>

GameShopRP/Pages/Order.cshtml
@page
@model GameShopRP.Pages.OrderModel
@{
    ViewData["Title"] = "Order";
}


    <div class="container">

        @if (Model.OrderViewModel.OrderItems.Any())
        {
            <div class="row my-2 px-3">
                <div class="col-auto">
                    <div style="width: 24px"></div>
                </div>
                <div class="col-auto"><h5 style="width: 70px">Product</h5></div>
                <div class="col-4 d-flex justify-content-center"></div>
                <div class="col d-flex justify-content-center"><h5>Price</h5></div>
                <div class="col d-flex justify-content-center"><h5>Quantity</h5></div>
                <div class="col d-flex justify-content-center"><h5>Cost</h5></div>
            </div>

            <hr />

            @foreach (var orderItem in Model.OrderViewModel.OrderItems)
            {
                <div class="border border-light-gray row rounded my-3 py-2 px-3">
                    <div class="col-auto d-flex align-items-center">
                        <form asp-page-handler="deleteOrderLine" method="post">
                            <button type="submit" class="catalog-button-hidden">
                                <svg class="ico" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
                                    <polyline points="3 6 5 6 21 6">
                                    </polyline>
                                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                                    </path>
                                    <line x1="10" y1="11" x2="10" y2="17">
                                    </line>
                                    <line x1="14" y1="11" x2="14" y2="17">
                                    </line>
                                </svg>
                            </button>
                            <input type="hidden" asp-for="@orderItem.Id" name="orderLineId" />
                        </form>
                    </div>
                    <div class="col-auto">
                        <div>
                            <img src="@orderItem.ImageUrl" class="img-fluid just" style="max-width: 70px" />
                        </div>
                    </div>
                    <div class="col-4 d-flex align-items-center"><h5>@orderItem.ProductName</h5></div>
                    <div class="col d-flex align-items-center justify-content-center">$@orderItem.ProductPrice</div>
                    <div class="col d-flex align-items-center justify-content-center">
                        <form asp-page-handler="updateQuantity" method="post">
                            <div class="input-group">
                                <span class="input-group-prepend">
                                    <span class="input-group-text btn" id="decrBtn" onclick="decQuantity(@orderItem.Id)">
                                        <svg id="i-minus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="15" height="15" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                            <path d="M2 16 L30 16" />
                                        </svg>
                                    </span>
                                </span>
                                <input id="inp@(orderItem.Id)" type="text" asp-for="@orderItem.Quantity" class="form-control" maxlength="4" min="1" name="quantity" />
                                <input type="hidden" asp-for="@orderItem.Id" name="orderLineId"/>
                                <span class="input-group-append">
                                    <span class="input-group-text btn" id="incrBtn" onclick="incQuantity(@orderItem.Id)">
                                        <svg id="i-plus" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="15" height="15" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                            <path d="M16 2 L16 30 M2 16 L30 16" />
                                        </svg>
                                    </span>
                                </span>
                            </div>
                            <button type="submit" class="btn btn-block btn-secondary mt-2" style="font-size: 0.8rem">Update</button>
                        </form>
                    </div>
                    <div class="col d-flex align-items-center justify-content-center">$@Math.Round(orderItem.ProductPrice * orderItem.Quantity, 2)</div>
                </div>
            }

            <div class="row my-2">
                <div class="col-md-4 d-flex align-items-center pl-0">
                    <div class="pr-5 btn-block">
                        <a asp-page="Index" class="btn btn-block btn-secondary text-white">Continue Shopping</a>
                    </div>
                </div>
                <div class="col-md-4"></div>
                <div class="col-md-4 pr-0">
                    <div class="p-4 clearfix rounded" style="background-color: #e3f2fd">
                        <span class="float-left mb-2">Total:</span>
                        <span class="float-right mb-2">@Model.OrderViewModel.Total()</span>
                        <a class="btn btn-block btn-warning" style="display: inline-block">Checkout</a>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div>
                <h3>
                    Your cart is empty.
                </h3>
            </div>
        }
    </div>
    <script src="~/js/cart.js"></script>